### ISSUE TITLE
Secondary and tertiary greens have same RGB value

### ISSUE THREAD

**Issue by bkjohnson** [adhocteam/styleguide#14]
The RGB values for the tertiary green are identical to the secondary green.

![image](https://user-images.githubusercontent.com/2008881/43097271-29848816-8e81-11e8-855c-0b5740ea36fd.png)

The RGB value [here](https://github.com/adhocteam/styleguide/blob/6574af8a33702636c334903d6464691737ecf775/pages/colors.html#L38) should be `RGB: 205, 236, 219`.  I can open a PR later to fix the hardcoded value - should I look for a way to eliminate the copy-paste nature and see if I can display translated values from the color swatch itself?

**Comment by erikphansen** [comment]
The CMYK should also be updated. Not sure what values to use there. The RGB -> CMYK conversion tool that I looked at showed values of 13, 0, 7, 7 but that same tool showed 73, 0, 32, 29 for the Secondary Green (which is not what's being used right now). Perhaps a designer/UX person should weigh in on the CMYK question.
