### ISSUE TITLE
Add "intimacy" to sexual terms section

### ISSUE THREAD

**Issue by mobleyabbie** [adhocteam/styleguide#27]
**Problem Statement:**

In addition to the prohibition on _sexy_, we should refrain from saying we're _intimate_ with the customer.

**Why is this valuable:**

The term _intimate_ is too loaded for professional correspondence. 

**Desired behavior:**

1. Update section of style guide.

Include screenshots, mock-ups, etc. as appropriate

**Acceptance Criteria:**

- [ ] First criteria

**Background/Context:**

Any related issues, prior art, inspiration, Slack discussions, etc.

**Security implications/assets interacted with:**

Any potential security or data concerns this may pose

**Comment by awfrancisco** [comment]
Good call, I'll get that added.

**Comment by awfrancisco** [comment]
[Added!](https://github.com/adhocteam/styleguide/commit/d04d3e2838dd316a0ab993fd59f7dccea4e02354)
